heat_template_version: 2013-05-23

description: >
  This template creates 2 hosts. Each Host is connected to a private network. A router is 
  created with one interface per subnet to allow host connectivity.


resources:
  test_network_1:
    type: OS::Neutron::Net
    properties:
      name: test_network_1

  test_subnet_1:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: test_network_1 }
      name: test_subnet_1
      cidr: 5.0.0.0/24
      gateway_ip: 5.0.0.1
      allocation_pools:
        - start: 5.0.0.100
          end: 5.0.0.200
  host1:
    type: OS::Nova::Server
    properties:
      name: host1
      image: cirros-0.3.2-x86_64-uec
      flavor: m1.tiny
      networks:
        - port: { get_resource: host1_port }

  host1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: test_network_1 }
      fixed_ips:
        - subnet_id: { get_resource: test_subnet_1 }

  test_network_2:
    type: OS::Neutron::Net
    properties:
      name: test_network_2

  test_subnet_2:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: test_network_2 }
      name: test_subnet_2
      cidr: 6.0.0.0/24
      gateway_ip: 6.0.0.1
      allocation_pools:
        - start: 6.0.0.100
          end: 6.0.0.200
  host2:
    type: OS::Nova::Server
    properties:
      name: host2
      image: cirros-0.3.2-x86_64-uec
      flavor: m1.tiny
      networks:
        - port: { get_resource: host2_port }

  host2_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: test_network_2 }
      fixed_ips:
        - subnet_id: { get_resource: test_subnet_2 }

  router:
    type: OS::Neutron::Router

  router_interface1:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: test_subnet_1 }

  router_interface2:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: test_subnet_2 }
